### ISSUE TITLE
Check Mac // Safari not adding turkey bug reported by Catherine Lee

### ISSUE THREAD

**Issue by ismu1** [sanctuarycomputer/smalls#10]

**Comment by joshiefishbein** [comment]
Do we have any information other than Safari on how to reproduce this?

**Comment by ismu1** [comment]
I just saw this comment from Matt:

So she said that she had selected all of the recipes (chicken, beef and turkey) and "All Smalls" seen here: https://cl.ly/3q293J2i0I0h and then when she checked out she only had this in her cart: https://cl.ly/1A2F2t1n1D3O

She was given a special promo code for 100% off so ignore the pricing. It's odd though, that she claims to have selected all of the recipes but they weren't all added. I think its 90% chance user error but I just want to be sure.

**Comment by joshiefishbein** [comment]
kk

I can actually reproduce this.

<img width="477" alt="screen shot 2017-10-26 at 3 49 27 pm" src="https://user-images.githubusercontent.com/7484028/32073847-673c3fdc-ba65-11e7-8ade-4b996fe9b379.png">

I selected all three recipes, All Smalls, 4 week delivery. Will look into.

**Comment by ismu1** [comment]
Additional comment: when you select turkey and beef you also get chicken in your chart.

**Comment by ismu1** [comment]
Sorry Joshie, but this is still not fixed when I try it :'(

Both issues:
1. Turkey not added to cart
2. Chicken automatically gets added when selecting turkey and beef

**Comment by joshiefishbein** [comment]
I may have accidentally dragged this into QA, shouldn't have been marked as completed.
Still working on getting into this!
