### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by ismu1** [sanctuarycomputer/smalls#14]

**Comment by joshiefishbein** [comment]
@ismu1 send me that favicon~~~

**Comment by ismu1** [comment]
Hm, they moved this one back in their internal column, but yes, will definitely send over the favicon when I receive it and this ticket becomes relevant.

**Comment by ismu1** [comment]
I got the favicon, so will send over when you wanna crank on this ticket!

**Comment by joshiefishbein** [comment]
Send whenever @ismu1
