### ISSUE TITLE
Add apostrophe's to "Cats Plan" 

### ISSUE THREAD

**Issue by ismu1** [sanctuarycomputer/smalls#2]
Add apostrophe's to "Cats Plan" (Should be "Cat's Plan") everywhere

**Comment by joshiefishbein** [comment]
I did this for:
- One CTA in the header
- Two CTAs on the homepage
- One CTA in Reviews
- One CTA in Food

Let me know if I've missed a spot, all of the above should be taken care of.

**Comment by ismu1** [comment]
He just added this one as well:

![image-1-2](https://user-images.githubusercontent.com/31043279/32023914-c9497ab8-b9a8-11e7-9622-0ff156aa83f4.jpg)

**Comment by joshiefishbein** [comment]
Done in the CMS
