### ISSUE TITLE
Set up Fullstory

### ISSUE THREAD

**Issue by ismu1** [sanctuarycomputer/smalls#20]
username: matt@smallsforsmalls.com
pw: MeowMeow2865

**Comment by joshiefishbein** [comment]
@ismu1 All set! He just needs to activate the account with a paid tier. After he's done with that I might need to do a little more configuration, otherwise I think we're set.

**Comment by ismu1** [comment]
alright so I got the trial extended and started to watch some sessions but it looks like they are getting cut off as soon as someone clicks on "see you cats plan"

here is an example: https://fsty.io/v/ajmyU7f

I think this is probably because the tracking code or whatever you want to call it in this case was put in maybe the header or footer which might not exist in the sign up flow? Just a theory.
