### ISSUE TITLE
Change Button Copy & Functionality (Nutritional Labels)

### ISSUE THREAD

**Issue by ismu1** [sanctuarycomputer/smalls#27]
Food page (after you've gone through QA)

See here for detailed explanation. https://cl.ly/2e3p232J340L
(Isabel: The button currently looks like this https://cl.ly/110J401I3o0p)

Change copy to "See Smalls Full Nutritional Labels"

Matt: The button should somehow reveal or show users the full labels. A lightbox could work? open to suggestions? Could even just download the pdfs. Labels attached.

Isabel: Joshie, let's talk about what you think here? I personally like lightboxes more than having to download a pdf on a site. I've the 3 nutritional labels (chicken, beef, turkey) which I'll send over when you get to this one.

**Comment by joshiefishbein** [comment]
@ismu1 I'm not sure what this ticket is asking for

**Comment by ismu1** [comment]
So he sent me 3 pdfs with nutritional information that he wants to link to that specific button. He is either suggesting it to show up in a lightbox or just being able to download the pdfs when you click that specific button, but he wants to know our opinion. We can talk more about this!

Just sent you the 3 pdfs.
