### ISSUE TITLE
Set up Segment

### ISSUE THREAD

**Issue by ismu1** [sanctuarycomputer/smalls#5]
Set up Segment w/ integrations for Facebook, Adwords and Google Analytics

Matt comments:
To get things started, I’d like to keep the analytics really straight forward. Outside of the site wide tracking that monitors behavior sitewide, I’d like to create events for folks who click on “see my cat’s plan” (which we can call “begin-onboarding”) and enter the on-boarding process and then users who complete checkout.

Overtime, we can develop a more robust analytics strategy but I think this is covers the absolute basics.

HASOFFERS: 
https://help.tune.com/hasoffers/pixel-tracking/
https://www.youtube.com/watch?v=aXsfcBa9Vdk

SEGMENT:
matt@smallsforsmalls.com
pw: Cadavre123

**Comment by ismu1** [comment]
Comments from Matt:

BIG PICTURE:
I'd like to first make sure the basics are 100% working properly and then try to add a few conversion events to better track how people are moving through the on-boarding flow.

ADWORDS:
I'm not sure if Adwords is firing properly: https://cl.ly/3c0G411d0q0Y. It still says "unverified" so I'm not quite sure what's going on.

I'd also like to track "begin on-boarding" in Adwords. Ive added the conversion in Adwords and tried to link it in segement.

FACEBOOK: 
Seems to be working properly! The purchase count seems to be about right so I think it's firing correctly.

GOOGLE ANALYTICS: 
So, I'm seeing that the event "purchase" and "begin on-boarding" are pulling through but it doesn't look like the purchase event is set up as the e-commerce transaction. I set up purchase and begin on-boarding as goals so it works for now, but I have a feeling setting it up as the e-commerce transaction might be better? Open to feedback.

ADDITIONAL TRACKING: 
My gut is that we should add tracking for when (1) someone moves past the "my name is and my email is" section by clicking continue. When someone (2) completes the questionnaire about their cats and clicks continue to recipes. (3) when someone clicks continue to shipping.

**Comment by ismu1** [comment]
@joshiefishbein Hey, I found it here: https://adwords.google.com/aw/conversions?ocid=202589937&__c=2988670950&authuser=0&__u=7172392242

https://cl.ly/0D1d320f1h3s

It still says Unverified on AdWords.

**Comment by joshiefishbein** [comment]
How do I get there? I can't click direct links to AdWords. @ismu1

**Comment by joshiefishbein** [comment]
nvm found it!

**Comment by joshiefishbein** [comment]
@ismu1 going forward let's split tickets up as small as possible. Each problem with each integration into Segment should be it's own deal.
